server:
  port: 8000

spring:
  datasource:
    name: ibookingdb
    url: jdbc:mysql://localhost:3306/ibooking?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: never

  thymeleaf:
    cache: false

  mvc:
    static-path-pattern: /**

logging:
  level:
    com.huawei.ibooking: debug


mybatis-plus:
  mapper-locations: classpath:com.huawei.ibooking.mapper/*.xml
  type-aliases-package: com.huawei.ibooking.model
  configuration:
    map-underscore-to-camel-case: false
    call-setters-on-nulls: true
  global-config:
    db-config:
      id-type: auto

